# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 01 - Tap Counter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project 01 - Tap Counter
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'HXTool'
	pod 'SnapKit'
end
