# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 04 - Tip Calculator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project 04 - Tip Calculator
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'SnapKit'
end
